### ISSUE TITLE
No Nix package

### ISSUE THREAD

**Issue by krankenwaerter** [donovanglover/thud#21]
Hello!
This project looks interesting. Unfortunately it can't be installed on NixOS per your [instructions](https://github.com/donovanglover/thud#nixos-recommended). Apparently your [PR](https://github.com/NixOS/nixpkgs/pull/249224) hasn't been merged yet...

**Comment by donovanglover** [comment]
Hey, thanks for making this issue.

I updated the PR to fix merge conflicts. I'll try to get it merged soon.

In the meantime, I [updated the README](https://github.com/donovanglover/thud/commit/534ca4f33b291c22474de37de58da78a89456064) to remove the incorrect instructions.

**Comment by donovanglover** [comment]
thud is [now available in `nixos-unstable`](https://nixpk.gs/pr-tracker.html?pr=249224). Enjoy!
